apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalyst-go-app.fullname" . }}
  labels:
    {{- include "catalyst-go-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.gateway.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
  selector:
    {{- include "catalyst-go-app.selectorLabels" . | nindent 4 }}
