{{- if .Values.appstore.cockroachdb.init.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalyst-go-app.fullname" . }}-cockroachdb-init-secrets
  labels:
    {{- include "catalyst-go-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.appstore.cockroachdb.init.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
